config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: "pages#home"

  get 'about', to: "pages#about"

  resources :jobs, only: %i[index new create show edit update destroy] do
    collection do
      get 'created'
    end
    resources :applications, only: [:create, :index]
  end

  resources :bookmarks, only: [:index, :create, :destroy]

  resources :applications, only: [:index, :create, :show]

  resources :users, only: [:show, :update, :edit, :destroy]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, :description, :company_name, :location, :price, :industry, presence: true
  has_many :applications, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  belongs_to :user

  INDUSTRY_COLORS = {
    "Software Development" => '#f5f3c4',
    "Finance & Accounting" => '#c4dcf5',
    "Architecture" => '#c4f5c6',
    "Marketing & Graphic Design" => '#f5c4e1',
    "Photography" => '#c4c6f5',
    "Video & Film" => '#c4f5c5',
    "Fashion" => '#f5dac4'
  }
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
    @jobs = @jobs.where("title ILIKE ?", "%#{params[:title]}%") if params[:title].present?
    @jobs = @jobs.where("location ILIKE ?", "%#{params[:location]}%") if params[:location].present?
    @jobs = @jobs.where(industry: params[:industry]) if params[:industry].present?
    @jobs = @jobs.where("price <= ?", params[:price_range]) if params[:price_range].present?

    if params[:tags].present?
      tags = Array(params[:tags]).reject(&:blank?).map { |tag| tag.split.map(&:capitalize).join(' ') }
      tags.each do |tag|
        @jobs = @jobs.where("? = ANY(tags)", tag)
      end
    end

    @jobs = @jobs.page(params[:page]).per(12)

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def new
    @job = Job.new
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to @job, notice: 'Job was successfully updated.'
    else
      render :edit
    end
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user

    # Parse tags if present
    if params[:job][:tags].present?
      @job.tags = JSON.parse(params[:job][:tags])
    end

    if @job.save
      redirect_to jobs_path, notice: 'Job created successfully.'
    else
      render :new
    end
  end

  def created
    @jobs = Job.where(user_id: current_user.id)
    @applications = Application.where(job_id: @jobs.pluck(:id))
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    flash[:notice] = 'Job was successfully deleted.'
    redirect_to jobs_path, status: :see_other
  end


  private

  def job_params
    params.require(:job).permit(:title, :company_name, :description, :start_date, :end_date, :price, :location, :time_commitment, :industry)
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/created.html.erb
<% if current_user.employer? %>
  <div class="flex items-center justify-between text-white mx-auto mt-6 p-6 w-3/4">
    <div class="flex items-center space-x-4">
      <div class="flex items-center justify-center border-gray-300 hover:border-primary-orange border-2 rounded-full p-2 w-20 h-20">
        <% if current_user.photo.attached? %>
          <%= image_tag current_user.photo, class: "w-full h-full object-cover rounded-full" %>
        <% else %>
          <svg xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 448 512">
            <path fill="#d1d5db" d="M304 128a80 80 0 1 0 -160 0 80 80 0 1 0 160 0zM96 128a128 128 0 1 1 256 0A128 128 0 1 1 96 128zM49.3 464l349.5 0c-8.9-63.3-63.3-112-129-112l-91.4 0c-65.7 0-120.1 48.7-129 112zM0 482.3C0 383.8 79.8 304 178.3 304l91.4 0C368.2 304 448 383.8 448 482.3c0 16.4-13.3 29.7-29.7 29.7L29.7 512C13.3 512 0 498.7 0 482.3z"/>
          </svg>
        <% end %>
      </div>
      <div class="flex flex-col">
        <div class="text-xl font-semibold"><%= current_user.name %></div>
        <div class="text-sm"><%= current_user.email %></div>
        <div class="text-sm"><%= current_user.location %></div>
      </div>
    </div>
    <button class="p-2 rounded-lg text-gray-300 border border-primary-orange hover:bg-primary-orange ease-in-out duration-300">
      <%= link_to "Edit Profile", edit_user_registration_path, data: { turbo_method: :get } %>
    </button>
  </div>
<% end %>

<div class="flex flex-row my-4 w-full justify-between">
  <div class="flex flex-col p-4 text-white w-1/2">
    <h1 class="text-2xl mb-5 pb-2 border-b-2 border-primary-orange w-3/4 text-center mx-auto">Your posted jobs</h1>
    <% if @jobs.any? %>
      <ul class="space-y-4 mx-auto">
        <% @jobs.each do |job| %>
          <div class="flex flex-row justify-between space-x-12">
            <li><%= job.title %> </li>
            <div class="flex flex-row gap-4">
              <%= link_to edit_job_path(job), class: "h-5" do %>
                <%= image_tag "pencil_icon.svg", data: { turbo_method: :patch }, size: "20x20", alt: "Pencil Icon" %>
              <% end %>
              <%= link_to job_path(job), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "h-5" do %>
                <%= image_tag "trash_icon.svg", size: "18x18", alt: "Trash Icon" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </ul>
    <% else %>
      <div class="flex flex-col items-center">
        <p class="text-center">You have not created any jobs yet.</p>
        <div class="hover:text-primary-orange border border-primary-orange rounded-lg p-2 my-4">
          <%= link_to "New Job", new_job_path, data: { turbo_method: :get } %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="flex flex-col p-4 text-white w-1/2 ">
    <h1 class="text-2xl mb-5 pb-2 border-b-2 border-primary-orange w-3/4 text-center mx-auto">Received applications</h1>
    <% if @applications.any? %>
      <ul>
        <% @applications.each do |application| %>
          <div class="px-2 py-1 rounded-lg border border-white w-3/4 mb-2 mx-auto">
            <li><%= application.job.title %></li>
            <div class="text-xs mb-2 font-light">Applied on: <%= application.created_at.strftime("%b %d, %Y") %></div>
            <li>Applicant name: <%= application.job.user.name %></li>
            <li>Applicant email: <%= application.job.user.email %></li>
            <div class="text-xs mt-2 font-light text-primary-orange">Download:</div>
            <div class="flex justify-between text-sm">
              <% if application.resume.present? %>
                <div>
                  <%= link_to 'Resume', url_for(application.resume), download: application.resume.filename.to_s, class:"hover:text-primary-orange" %>
                </div>
              <% end %>
              <% if application.cover_letter.present? %>
                <div>
                  <%= link_to 'Cover Letter', url_for(application.cover_letter), download: application.cover_letter.filename.to_s, class:"hover:text-primary-orange mr-20" %>
                </div>
              <% end %>
            </div>
            <% if application.personal_message.present? %>
              <div class="text-xs mt-2 font-light text-primary-orange">Personal message:</div>
              <div class="text-sm"><%= application.personal_message %></div>
            <% end %>
          </div>
        <% end %>
      </ul>
    <% else %>
      <p class="text-center">You have not received any applications</p>
    <% end %>
  </div>
</div>

app/views/jobs/edit.html.erb
<div class="flex items-center justify-center p-12">
  <div class="mx-auto w-2/5">
    <%= form_with(model: @job, url: job_path(@job), method: :patch) do |form| %>
      <div class="-mx-3 flex flex-wrap">
        <div class="w-full px-3 sm:w-1/2">
          <div class="mb-5">
            <%= form.label :title, "Job Title *", class: "mb-3 block text-base font-medium text-gray-300" %>
            <%= form.text_field :title, placeholder: "Job Title", class: "w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" %>
          </div>
        </div>
        <div class="w-full px-3 sm:w-1/2">
          <div class="mb-5">
            <%= form.label :company_name, "Company Name *", class: "mb-3 block text-base font-medium text-gray-300" %>
            <%= form.text_field :company_name, placeholder: "Company Name", class: "w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" %>
          </div>
        </div>
      </div>

      <div class="mb-5">
        <%= form.label :description, "Detailed job description *", class: "mb-3 block text-base font-medium text-gray-300" %>
        <%= form.text_area :description, placeholder: "Enter details about the job", class: "w-full appearance-none rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" %>
      </div>

      <div class="-mx-3 flex flex-wrap">
        <div class="w-full px-3 sm:w-1/2">
          <div class="mb-5">
            <%= form.label :start_date, "Start Date", class: "mb-3 block text-base font-medium text-gray-300" %>
            <%= form.date_field :start_date, class: "w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" %>
          </div>
        </div>
        <div class="w-full px-3 sm:w-1/2">
          <div class="mb-5">
            <%= form.label :end_date, "End Date", class: "mb-3 block text-base font-medium text-gray-300" %>
            <%= form.date_field :end_date, class: "w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" %>
          </div>
        </div>
      </div>

      <div class="mb-5">
        <%= form.label :price, "Price per month or job *", class: "mb-3 block text-base font-medium text-gray-300" %>
        <%= form.text_field :price, class: "w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md", placeholder:"$" %>
      </div>

      <div class="mb-5">
        <%= form.label :location, "Location *", class: "mb-3 block text-base font-medium text-gray-300" %>
        <%= form.text_field :location, class: "w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" %>
      </div>

      <div data-controller="industry-dropdown">
        <%= form.label :industry, "Industry *", class: "mb-3 block text-base font-medium text-gray-300" %>
        <!-- Dropdown Button -->
        <button
          class="flex justify-between w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
          type="button"
          data-dropdown-toggle="industry-dropdown"
        >
          <span data-industry-dropdown-target="output"><%= @job.industry || "Select an Industry" %></span>
          <svg class="w-2.5 h-2.5 items-center align-middle my-auto" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
          </svg>
        </button>
        <!-- Dropdown menu -->
        <div
          data-industry-dropdown-target="selected"
          id="industry-dropdown"
          class="z-10 hidden bg-white divide-x divide-gray-300 rounded-lg shadow w-2/5 dark:bg-gray-700"
        >
          <ul class="py-2 text-sm text-gray-700 dark:text-gray-200">
            <li>
              <a href="#" data-value="Software Development" data-action="click->industry-dropdown#selectItem" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Software Development</a>
            </li>
            <li>
              <a href="#" data-value="Finance & Accounting" data-action="click->industry-dropdown#selectItem" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Finance & Accounting</a>
            </li>
            <li>
              <a href="#" data-value="Architecture" data-action="click->industry-dropdown#selectItem" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Architecture</a>
            </li>
            <li>
              <a href="#" data-value="Marketing & Graphic Design" data-action="click->industry-dropdown#selectItem" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Marketing & Graphic Design</a>
            </li>
            <li>
              <a href="#" data-value="Photography" data-action="click->industry-dropdown#selectItem" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Photography</a>
            </li>
            <li>
              <a href="#" data-value="Fashion" data-action="click->industry-dropdown#selectItem" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Fashion</a>
            </li>
            <li>
              <a href="#" data-value="Video & Film" data-action="click->industry-dropdown#selectItem" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Video & Film</a>
            </li>
          </ul>
        </div>
        <%= form.hidden_field :industry, id: "industry-hidden-field" %>
      </div>

      <button class="rounded-md py-3 px-8 mt-5 text-center font-semibold text-gray-100 bg-primary-orange w-full">
        <%= form.submit "Update Job", class: "hover:cursor-pointer" %>
      </button>
    <% end %>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="py-8 px-4 mx-auto w-1/2 rounded-xl">
  <%= link_to :back do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="mb-4" height="20" width="17.5" viewBox="0 0 448 512"><path fill="#d1d5db" d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg>
  <% end %>
  <div class="border-b border-gray-400">
    <div class="flex flex-row justify-between">
      <div class="text-gray-200 text-3xl"><%= @job.title %></div>
        <svg xmlns="http://www.w3.org/2000/svg"
            class="mr-1 cursor-pointer  mt-1"
            height="26" width="24"
            viewBox="0 0 384 512"
            data-action="click->save#saveJob"
            data-controller="save"
            data-save-target="svg"
            data-job-id="<%= @job.id %>">
            <path fill="<%= current_user.applications.pluck(:job_id).include?(@job.id) ? "orange" : "#d1d5db" %>" d="M0 48C0 21.5 21.5 0 48 0l0 48 0 393.4 130.1-92.9c8.3-6 19.6-6 27.9 0L336 441.4 336 48 48 48 48 0 336 0c26.5 0 48 21.5 48 48l0 440c0 9-5 17.2-13 21.3s-17.6 3.4-24.9-1.8L192 397.5 37.9 507.5c-7.3 5.2-16.9 5.9-24.9 1.8S0 497 0 488L0 48z"/>
          </svg>
    </div>
    <div class="font-light text-primary-orange pt-1">
      <%= @job.industry %>
    </div>
    <div class="flex flex-row justify-between pt-1 pb-3">
      <div class="text-gray-400"><%= @job.company_name %></div>
      <div class="text-gray-400"><%= @job.location %></div>
    </div>
  </div>
<%# Job Details %>
  <div class="pt-6 pb-4">
    <p class="text-gray-400 text-xs">About:</p>
    <div class="text-gray-300"><%= @job.description %></div>
  </div>
  <div class="flex flex-row justify-between border-b border-gray-400 pb-6 ">
    <div>
      <div class="text-gray-300">Start Date: <%= @job.start_date.strftime("%b %d, %Y") %></div>
      <div class="text-gray-300">End Date: <%= @job.end_date.strftime("%b %d, %Y") %></div>
    </div>
    <div class="text-gray-300 text-lg">$<%= @job.price %> per month</div>
  </div>
<%# Apply Section %>
<%= form_with(model: Application.new, url: applications_path, method: "post", multipart: true) do |form| %>
    <div class="flex flex-col">
      <div class="flex flex-row my-3">
        <div class="pr-2">
          <%= form.label :resume, "Upload Resume", class:"block mb-2 text-sm  text-gray-300"  %>
          <%= form.file_field :resume, class:"block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 focus:outline-none" %>
          <p class="mt-1 text-sm text-gray-500" id="file_input_help">.doc, .docx, .pdf, .html (max. 20mb).</p>
        </div>
        <div class="pr-2">
          <%= form.label :cover_letter, "Upload Cover Letter", class:"block mb-2 text-sm  text-gray-300"  %>
          <%= form.file_field :cover_letter, class:"block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 focus:outline-none" %>
          <p class="mt-1 text-sm text-gray-500" id="file_input_help">.doc, .docx, .pdf, .html (max. 20mb).</p>
        </div>
      </div>
      <%= form.label :personal_message, "Personal Message (optional)", class:"block mb-2 text-sm text-gray-300" %>
      <%= form.text_area :personal_message, class:"block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-primary-orange focus:border-primary-orange "  %>
    </div>
<%# Button %>
    <div class="w-full justify-center text-center my-2">
      <button class= "px-6 py-2 rounded-full bg-primary-orange text-gray-100 my-4 font-semibold w-1/2">
          <%= form.submit "Apply", class:"hover:cursor-pointer" %>
          <%= form.hidden_field :user_id, value: current_user.id %>
          <%= form.hidden_field :job_id, value: @job.id %>
      </button>
    </div>
<% end %>