config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: "pages#home"

  get 'about', to: "pages#about"

  resources :jobs, only: %i[index new create show edit update destroy] do
    collection do
      get 'created'
    end
    resources :applications, only: [:create, :index]
  end

  resources :bookmarks, only: [:index, :create, :destroy]

  resources :applications, only: [:index, :create, :show]

  resources :users, only: [:show, :update, :edit, :destroy]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_button_animated.html.erb
<a href="<%= href %>" class="container inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center text-white rounded-lg bg-primary-orange hover:bg-orange-400 focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-900 <%= local_assigns[:custom_classes] %>">
  <div class="bottom"></div>
  <div class="cover cut"></div>
  <div class="text-container">
    <div class="text text-dark"><%= text %></div>
  </div>
  <div class="text-container cut">
    <div class="text"><%= text %></div>
  </div>
  <div class="overlay"></div>
</a>


<script type="module">
    const bottom = document.querySelector(".bottom");
    const overlay = document.querySelector(".overlay");
    const count = 110;
    const size = 50;
    for (let i = 0; i <= count; i += 1) {
      const dot = document.createElement("div");
      dot.classList.add("dot");
      bottom.appendChild(dot);
    }
    const dots = Array.from(document.querySelectorAll(".dot"));

    const updateText = (text) => {
      Array.from(document.querySelectorAll(".text")).forEach(
        (e) => (e.innerHTML = text)
      );
    };

    const reset = () => {
      dots.forEach((dot, i) => {
        const x = (i / count) * (190 + size) - size / 2;
        const y = Math.random(1) * 52 - size / 2;
        dot.style.width = `${size}px`;
        dot.style.height = `${size}px`;
        dot.style.left = `${x}px`;
        dot.style.top = `${y}px`;
        dot.style.opacity = 1;
        dot.style.transform = "scale(1)";
      });
    };
    reset();

    overlay.addEventListener("click", () => {
      anime({
        easing: "linear",
        targets: document.querySelectorAll(".dot"),
        opacity: [{ value: 0, duration: 600, delay: anime.stagger(10) }],
        translateX: {
          value: function () {
            return anime.random(-30, 30);
          },
          duration: 400,
          delay: anime.stagger(10)
        },
        translateY: {
          value: function () {
            return anime.random(-30, 30);
          },
          duration: 400,
          delay: anime.stagger(10)
        },
        scale: {
          value: function () {
            return 0;
          },
          duration: 400,
          delay: anime.stagger(10)
        }
      });
      anime({
        easing: "linear",
        delay: 4000,
        complete: () => {
          updateText("Submitted");
          setTimeout(() => {
            updateText("Submit");
            reset();
          }, 3000);
        }
      });
    });

</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative m-1" role="alert">
    <button type="button" class="absolute top-0 right-0 mr-1 mt-1" data-dismiss="alert" aria-label="Close">
      <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M14.95 5.636l-1.414-1.414L10 8.586 6.464 5.121 5.05 6.535 8.586 10l-3.535 3.535 1.414 1.414L10 11.414l3.536 3.536 1.414-1.414L11.414 10l3.535-3.535z"/></svg>
    </button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="bg-yellow-100 border border-yellow-400 text-yellow-700 px-4 py-3 rounded relative m-1" role="alert">
    <button type="button" class="absolute top-0 right-0 mr-1 mt-1" data-dismiss="alert" aria-label="Close">
      <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M14.95 5.636l-1.414-1.414L10 8.586 6.464 5.121 5.05 6.535 8.586 10l-3.535 3.535 1.414 1.414L10 11.414l3.536 3.536 1.414-1.414L11.414 10l3.535-3.535z"/></svg>
    </button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-transparent rounded-lg shadow m-4">
    <div class="w-full max-w-screen-xl mx-auto p-4 md:py-8">
        <div class="sm:flex sm:items-center sm:justify-between">
            <a href="https://flowbite.com/" class="flex items-center mb-4 sm:mb-0 rtl:space-x-reverse">
                <%= image_tag("moreXP_logo2.png", class:"h-8", alt: "moreXPLogo") %>
                <span class="self-center text-2xl font-semibold whitespace-nowrap text-gray-300">moreXP</span>
            </a>
            <ul class="flex flex-wrap items-center mb-6 text-sm font-medium text-gray-500 sm:mb-0 dark:text-gray-400">
                <li>
                    <a href="#" class="hover:underline me-4 md:me-6">About</a>
                </li>
                <li>
                    <a href="#" class="hover:underline me-4 md:me-6">Privacy Policy</a>
                </li>
                <li>
                    <a href="#" class="hover:underline me-4 md:me-6">Licensing</a>
                </li>
                <li>
                    <a href="#" class="hover:underline">Contact</a>
                </li>
            </ul>
        </div>
        <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
        <span class="block text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2024 <a href="https://flowbite.com/" class="hover:underline">moreXP™</a>. All Rights Reserved.</span>
    </div>
</footer>

app/views/shared/_job_card.html.erb
<div class="grid grid-cols-2 md:grid-cols-4 gap-4 w-full pt-5 mx-auto" >
  <% jobs.each do |job| %>
    <div class="flex flex-col place-content-between p-2 rounded-lg h-[25vh]" style="background-color: <%= Job::INDUSTRY_COLORS[job.industry] %>">
      <div class="flex flex-row justify-between">
        <div class="text-sm"><%= job.created_at.strftime("%b %d, %Y") %></div>

          <svg xmlns="http://www.w3.org/2000/svg"
            class="mr-1 cursor-pointer text-white"
            height="16" width="15"
            viewBox="0 0 384 512"
            data-action="click->save#saveJob"
            data-controller="save"
            data-save-target="svg"
            data-job-id="<%= job.id %>">

            <path fill="<%= user_signed_in? && current_user.bookmarks.exists?(job_id: job.id) ? 'orange' : '#1f2937' %>" d="M0 48C0 21.5 21.5 0 48 0l0 48 0 393.4 130.1-92.9c8.3-6 19.6-6 27.9 0L336 441.4 336 48 48 48 48 0 336 0c26.5 0 48 21.5 48 48l0 440c0 9-5 17.2-13 21.3s-17.6 3.4-24.9-1.8L192 397.5 37.9 507.5c-7.3 5.2-16.9 5.9-24.9 1.8S0 497 0 488L0 48z"/>
          </svg>

      </div>
      <div>
        <div class="text-xs text-gray-600"><%= job.company_name %></div>
        <div class=""><%= job.title %></div>

      </div>
      <div class="flex flex-row justify-between">
        <div>
          <div class="text-xs">$<%= job.price %> /mo</div>
          <div class="text-xs"><%= job.location %></div>
        </div>
        <button class="px-2 rounded-2xl text-xs text-gray-300 hover:text-primary-orange" style="background-color: rgb(4, 39, 62)">
          <%= link_to "Details", job_path(job), data: { turbo_method: :get , turbo_frame: "_top" } %>
        </button>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_letterize.html.erb
<div class="letterize">
      <div class="animate-me">
      +Experience+Opporunity.
      </div>
      <div class="animate-me">
      +Opporunity+Experience.
      </div>
      <div class="animate-me">
      +Experience+Opporunity.
      </div>
      <div class="animate-me">
      +Opporunity+Experience.
      </div>
      <div class="animate-me">
      +Experience+Opporunity.
      </div>
      <div class="animate-me">
      +Opporunity+Experience.
      </div>
      <div class="animate-me">
      +Experience+Opporunity.
      </div>
      <div class="animate-me">
      +Opporunity+Experience.
      </div>
      <div class="animate-me">
      +Experience+Opporunity.
      </div>
      <div class="animate-me">
      +Opporunity+Experience.
      </div>
      <div class="animate-me">
      +Experience+Opporunity.
      </div>
      <div class="animate-me">
      +Opporunity+Experience.
      </div>
      <div class="animate-me">
      +Experience+Opporunity.
      </div>
      <div class="animate-me">
      +Opporunity+Experience.
      </div>
    </div>

<%# <script src="anime.min.js"></script> %>
<script type="module">
  import Letterize from "https://cdn.skypack.dev/letterizejs@2.0.0";
  import anime from "https://cdn.skypack.dev/animejs@3.2.1";

  document.addEventListener("DOMContentLoaded", () => {
    const test = new Letterize({
      targets: ".animate-me"
    });

    const animation = anime.timeline({
      targets: test.listAll,
      delay: anime.stagger(100, {
        grid: [test.list[0].length, test.list.length],
        from: "center"
      }),
      loop: true
    });

    animation
      .add({
        scale: 0.5
      })
      .add({
        letterSpacing: "10px"
      })
      .add({
        scale: 1
      })
      .add({
        letterSpacing: "6px"
      });
  });
</script>

app/views/shared/_navbar.html.erb
<nav class="border-b-2 rounded-b-3xl px-6 py-6 text-gray-300 z-0" style="background-color: rgb(55, 97, 125); border: 1px solid rgb(55, 97, 125);">
  <div class="flex justify-between mx-auto">
    <%= link_to "Browse", jobs_path, data: { turbo_method: :get }, class:"hover:text-primary-orange ml-5 text-lg mt-1" %>
    <ul class="flex flex-row justify-between space-x-2 ">
      <% if user_signed_in? %>
        <ul class="flex flex-row justify-between space-x-2 items-center">
          <div class="flex flex-row mr-20 hover:text-primary-orange hover:fill-primary-orange">
            <svg xmlns="http://www.w3.org/2000/svg" height="20" width="15" class="" viewBox="0 0 384 512"><path fill="#d1d5db" d="M215.7 499.2C267 435 384 279.4 384 192C384 86 298 0 192 0S0 86 0 192c0 87.4 117 243 168.3 307.2c12.3 15.3 35.1 15.3 47.4 0zM192 128a64 64 0 1 1 0 128 64 64 0 1 1 0-128z"/></svg>
            <div class="ml-2 cursor-pointer"><%= current_user.location.present? ? current_user.location : "Your Location" %></div>
          </div>
          <%# Dropdown User Button %>
          <li id="dropdownDefaultButton" data-dropdown-toggle="dropdown" class="border-gray-300 hover:border-primary-orange border-2 rounded-full p-2"><svg xmlns="http://www.w3.org/2000/svg" height="18" width="18" viewBox="0 0 448 512"><path d="M304 128a80 80 0 1 0 -160 0 80 80 0 1 0 160 0zM96 128a128 128 0 1 1 256 0A128 128 0 1 1 96 128zM49.3 464l349.5 0c-8.9-63.3-63.3-112-129-112l-91.4 0c-65.7 0-120.1 48.7-129 112zM0 482.3C0 383.8 79.8 304 178.3 304l91.4 0C368.2 304 448 383.8 448 482.3c0 16.4-13.3 29.7-29.7 29.7L29.7 512C13.3 512 0 498.7 0 482.3z"/></svg></li>
          <%# Dropdown Settings Button %>
          <li data-dropdown-toggle="settings-dropdown" class="border-gray-300 hover:border-primary-orange border-2 rounded-full p-2"><svg xmlns="http://www.w3.org/2000/svg" height="18" width="18" viewBox="0 0 512 512"><path d="M495.9 166.6c3.2 8.7 .5 18.4-6.4 24.6l-43.3 39.4c1.1 8.3 1.7 16.8 1.7 25.4s-.6 17.1-1.7 25.4l43.3 39.4c6.9 6.2 9.6 15.9 6.4 24.6c-4.4 11.9-9.7 23.3-15.8 34.3l-4.7 8.1c-6.6 11-14 21.4-22.1 31.2c-5.9 7.2-15.7 9.6-24.5 6.8l-55.7-17.7c-13.4 10.3-28.2 18.9-44 25.4l-12.5 57.1c-2 9.1-9 16.3-18.2 17.8c-13.8 2.3-28 3.5-42.5 3.5s-28.7-1.2-42.5-3.5c-9.2-1.5-16.2-8.7-18.2-17.8l-12.5-57.1c-15.8-6.5-30.6-15.1-44-25.4L83.1 425.9c-8.8 2.8-18.6 .3-24.5-6.8c-8.1-9.8-15.5-20.2-22.1-31.2l-4.7-8.1c-6.1-11-11.4-22.4-15.8-34.3c-3.2-8.7-.5-18.4 6.4-24.6l43.3-39.4C64.6 273.1 64 264.6 64 256s.6-17.1 1.7-25.4L22.4 191.2c-6.9-6.2-9.6-15.9-6.4-24.6c4.4-11.9 9.7-23.3 15.8-34.3l4.7-8.1c6.6-11 14-21.4 22.1-31.2c5.9-7.2 15.7-9.6 24.5-6.8l55.7 17.7c13.4-10.3 28.2-18.9 44-25.4l12.5-57.1c2-9.1 9-16.3 18.2-17.8C227.3 1.2 241.5 0 256 0s28.7 1.2 42.5 3.5c9.2 1.5 16.2 8.7 18.2 17.8l12.5 57.1c15.8 6.5 30.6 15.1 44 25.4l55.7-17.7c8.8-2.8 18.6-.3 24.5 6.8c8.1 9.8 15.5 20.2 22.1 31.2l4.7 8.1c6.1 11 11.4 22.4 15.8 34.3zM256 336a80 80 0 1 0 0-160 80 80 0 1 0 0 160z"/></svg></li>
          <li class="border-gray-300 hover:border-primary-orange border-2 rounded-full p-2"><svg xmlns="http://www.w3.org/2000/svg" height="18" width="18" viewBox="0 0 448 512"><path d="M224 0c-17.7 0-32 14.3-32 32l0 19.2C119 66 64 130.6 64 208l0 25.4c0 45.4-15.5 89.5-43.8 124.9L5.3 377c-5.8 7.2-6.9 17.1-2.9 25.4S14.8 416 24 416l400 0c9.2 0 17.6-5.3 21.6-13.6s2.9-18.2-2.9-25.4l-14.9-18.6C399.5 322.9 384 278.8 384 233.4l0-25.4c0-77.4-55-142-128-156.8L256 32c0-17.7-14.3-32-32-32zm0 96c61.9 0 112 50.1 112 112l0 25.4c0 47.9 13.9 94.6 39.7 134.6L72.3 368C98.1 328 112 281.3 112 233.4l0-25.4c0-61.9 50.1-112 112-112zm64 352l-64 0-64 0c0 17 6.7 33.3 18.7 45.3s28.3 18.7 45.3 18.7s33.3-6.7 45.3-18.7s18.7-28.3 18.7-45.3z"/></svg></li>
        </ul>
        <%# Dropdown User %>
        <div id="dropdown" class="z-30 hidden bg-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
          <ul class="py-2 px-3 text-sm text-gray-700 space-y-3" aria-labelledby="dropdownDefaultButton">
            <% if current_user.employer? %>
              <li class="hover:text-primary-orange">
                <%= link_to "Profile", created_jobs_path, data: { turbo_method: :get } %>
              </li>
              <li class="hover:text-primary-orange">
                <%= link_to "New Job", new_job_path, data: { turbo_method: :get } %>
              </li>
            <% else %>
              <li class="hover:text-primary-orange">
                <%= link_to "Profile", user_path(current_user), data: { turbo_method: :get } %>
              </li>
            <% end %>

            <% if current_user.customer? || current_user.admin? %>
              <li class="hover:text-primary-orange">
                <%= link_to "Saved Jobs", bookmarks_path, data: { turbo_method: :get } %>
              </li>
              <li class="hover:text-primary-orange">
                <%= link_to "Sent Applications", applications_path(@applications), data: { turbo_method: :get } %>
              </li>
            <% end %>

            <% if current_user.admin? %>
              <li class="hover:text-primary-orange">
                <%= link_to "New Job", new_job_path, data: { turbo_method: :get } %>
              </li>
              <li class="hover:text-primary-orange">
                <%= link_to "Posted Jobs", created_jobs_path, data: { turbo_method: :get } %>
              </li>
            <% end %>
          </ul>
        </div>
        <%# Dropdown Settings %>
        <div id="settings-dropdown" class="z-30 hidden bg-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
            <ul class="py-2 px-3 text-sm text-gray-700 space-y-3 ">
              <li class="hover:text-primary-orange">
                <%= link_to "Edit User", edit_user_registration_path, data: { turbo_method: :get }  %>
              </li>
              <li class="hover:text-primary-orange">
                <%= link_to "Log Out", destroy_user_session_path, data: { turbo_method: :delete } %>
              </li>
            </ul>
        </div>
      <% else %>
        <%= link_to "Log In", new_user_session_path, data: { turbo_method: :get }, class:"hover:text-primary-orange mr-5 text-lg"  %>
      <% end %>
    </ul>
  </div>
  <%= link_to root_path do %>
    <%= image_tag("moreXP_logo2.png", class: "absolute left-1/2 transform -translate-x-1/2 -translate-y-1/2 h-[104px] w-[136px]", alt: "moreXPLogo") %>
  <% end %>
</nav>

app/views/shared/_saved_jobs.html.erb
  <div class="grid grid-cols-2 md:grid-cols-4 gap-4 w-3/4 pt-5 mx-auto">
        <% @bookmarks.each do |job| %>
          <div class="flex flex-col place-content-between p-2 rounded-lg h-[25vh]" style="background-color: <%= Job::INDUSTRY_COLORS[job.industry] %>"
            >
            <div class="flex flex-row justify-between">
              <div class="text-sm"><%= job.created_at.strftime("%b %d, %Y") %></div>
              <svg xmlns="http://www.w3.org/2000/svg"
                  class="mr-1 cursor-pointer text-white"
                  height="16" width="15"
                  viewBox="0 0 384 512"
                  data-action="click->save#saveJob"
                  data-controller="save"
                  data-save-target="svg"
                  data-job-id="<%= job.id %>">
                <path fill="<%= current_user.bookmarks.pluck(:job_id).include?(job.id) ? "orange" : "#1f2937" %>" d="M0 48C0 21.5 21.5 0 48 0l0 48 0 393.4 130.1-92.9c8.3-6 19.6-6 27.9 0L336 441.4 336 48 48 48 48 0 336 0c26.5 0 48 21.5 48 48l0 440c0 9-5 17.2-13 21.3s-17.6 3.4-24.9-1.8L192 397.5 37.9 507.5c-7.3 5.2-16.9 5.9-24.9 1.8S0 497 0 488L0 48z"/>
              </svg>
            </div>
            <div>
              <div class="text-xs text-gray-600"><%= job.company_name %></div>
              <div class=""><%= job.title %></div>
            </div>
            <div class="flex flex-row justify-between">
              <div>
                <div class="text-xs">$<%= job.price %> /mo</div>
                <div class="text-xs"><%= job.location %></div>
              </div>
              <button class="px-2 rounded-2xl text-xs text-gray-300 hover:text-primary-orange" style="background-color: rgb(4, 39, 62)">
                <%= link_to "Details", job_path(job), data: { turbo_method: :get } %>
              </button>
            </div>
          </div>
        <% end %>
      </div>

app/views/shared/_sent_applications.html.erb
<div class="mt-4">
  <% if @applications.any? %>
  <div class="font-semibold text-3xl text-gray-300 z-20 mx-36">Sent Applications</div>
    <% @applications.each do |application| %>
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4 w-3/4 pt-5 mx-auto">
        <div class="flex flex-col place-content-between p-2 bg-green-100 rounded-lg h-fit" style="background-color: <%= Job::INDUSTRY_COLORS[application.job.industry] %>">
          <% if application.applied_to? && user_signed_in? %>
            <div class="">
              <% if application.job.present? %>
                <div class="text-xs mb-2 font-light">Applied on: <%= application.created_at.strftime("%b %d, %Y") %></div>
                <div class="font-light"><%= application.job.company_name %></div>
                <div class="font-semibold"><%= application.job.title %></div>
                <div class="flex justify-between mt-2">
                  <div class="text-sm"><%= application.job.location %></div>
                  <div class="text-sm">$<%= application.job.price %> /mo</div>
                </div>
              <% end %>
              <div class="text-xs mt-2 font-light">Download:</div>
              <div class="flex justify-between text-sm">
                <% if application.resume.present? %>
                  <div>
                    <%= link_to 'Resume', url_for(application.resume), download: application.resume.filename.to_s, class:"hover:text-primary-orange" %>
                  </div>
                <% end %>
                <% if application.cover_letter.present? %>
                  <div>
                    <%= link_to 'Cover Letter', url_for(application.cover_letter), download: application.cover_letter.filename.to_s, class:"hover:text-primary-orange" %>
                  </div>
                <% end %>
              </div>
              <div class="flex justify-center mt-2">
                <button class="p-2 w-1/2 rounded-2xl text-xs text-gray-300 hover:text-primary-orange bg-custom-blue">
                  <%= link_to "Job Details", job_path(application.job), data: { turbo_method: :get } %>
                </button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>

  <% else %>
    <div class="w-screen mx-auto pt-20 content-center text-3xl text-center text-gray-300">
      <h1>No sent applications to show,<br> <%= link_to "Browse", jobs_path, data: { turbo_method: :get }, class: "text-primary-orange hover:text-gray-300" %> jobs to find your next experience opportunity!</h1>
    </div>
  <% end %>
</div>