config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: "pages#home"

  get 'about', to: "pages#about"

  resources :jobs, only: %i[index new create show edit update destroy] do
    collection do
      get 'created'
    end
    resources :applications, only: [:create, :index]
  end

  resources :bookmarks, only: [:index, :create, :destroy]

  resources :applications, only: [:index, :create, :show]

  resources :users, only: [:show, :update, :edit, :destroy]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/pages/about.html.erb
<div class="flex flex-col w-full justify-center content-center mx-auto my-8">
  <h1 class="text-center font-special text-4xl text-primary-orange">Welcome to MoreXP</h1>
  <div class="text-gray-300 px-40 py-5 space-y-2 mb-10">
    <p>This is an experimental application that challenges the conventional approach to finding a job.</p>
    <p>Inspired by the ever-increasing turmoil in the job market, where highly capable individuals struggle to find employment, especially their first job.</p>
    <p>MoreXP tackles this issue by allowing users to gain job experience across various industries to get their foot in the door.</p>
    <p>Whether it’s a single project, a few months of work, or an on-call part-time gig, these experiences will be valuable additions to their resumes.</p>
    <p>This approach effectively allows people to showcase their abilities, regardless of how well they perform in traditional interviews, which, sadly, is also a necessary skill in today’s job market.</p>
  </div>
  <div class="flex items-center mx-auto justify-between my-10">
    <%= render "shared/line_text" %>
  </div>
</div>

app/views/pages/home.html.erb
<%# Hero %>
<section>
    <div class="py-8 px-4 mx-auto max-w-screen-xl text-center my-28">
        <h1 id="main-title" class="gradient-text pb-4 font-extrabold tracking-tight leading-none text-7xl">It’s time to level up</h1>
        <p class="mb-8 text-lg font-normal text-gray-500 lg:text-xl md:px-60">It's impossible to find a job without experience.<br> It's impossible to get experience without a job.</p>
        <div class="flex flex-row space-x-4 sm:flex-row sm:justify-center sm:space-y-0">
          <%= render 'shared/button_animated', href: new_user_session_path, text: 'Get Started', custom_classes: 'text-lg' %>
          <%= render 'shared/button_animated', href: about_path, text: 'Learn More', custom_classes: 'text-lg'   %>
        </div>
        <div id="subtitle-text" class="font-special text-3xl text-gray-400 mt-10"> We're here to help you break into the industry.</div>
    </div>
</section>
<%# Steps %>

<%# <%= image_tag "path.svg", alt: "path", id: "path", class: "absolute top-[700px] left-40 w-full h-full" %>
<%#= image_tag "Side Head Lightbulb.svg", id: "side-head-light", alt: "text", class: " absolute h-20 w-20" %>
<section>
  <div class="mb-40 mx-10">
<%#= image_tag "plus_icon.svg", id: "plus-icon", alt: "plus-icon", class: "h-36 w-36 block" %>
    <div class="flex flex-col w-full gap-24 md:gap-96">
        <%# Step 1 %>
          <div class="w-3/4 mx-auto mt-24">
            <h1 id="step-1-text" class="text-4xl md:text-5xl text-center font-special text-primary-orange">.</h1>
          </div>
        <%# Step 2 %>
          <div class="w-1/2 mx-auto">
            <h1 id="step-2-text" class="text-4xl md:text-5xl text-center font-special text-primary-orange">.</h1>
          </div>
        </div>
        <%# Step 3 %>
        <div id="step-3" class="radial-bg flex w-full h-[400px] items-center justify-center mx-auto my-96 relative">
          <h1 id="step-3-text" class="text-4xl text-center leading-5 font-special text-custom-blue absolute transform scale-0">.</h1>
        </div>
          <div><%#= image_tag "plus_icon.svg", id: "plus-icon-2", alt: "plus-icon-2", class: "h-36 w-36" %></div>
      <div class="flex w-full mx-auto justify-center">
        <button id="browse-jobs-button" class="animate-bounce">
          <%= render 'shared/button_animated', href: jobs_path, text: 'Browse Jobs', custom_classes: 'text-xl py-20 px-24 rounded-md'  %>
        </button>
      </div>
    </div>
  </div>
</section>


<%= render "shared/footer" %>